security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        AppBundle\Entity\Admin\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: null }
        admin_db_provider:
            entity:
                class: AppBundle:Admin\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            anonymous: ~
            logout_on_user_change: true
            provider: admin_db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /admin
        main:
            anonymous: lazy

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
